const codeToLanguage = {
    'ab': 'abkhazian',
    'aa': 'afar',
    'af': 'afrikaans',
    'ak': 'akan',
    'sq': 'albanian',
    'am': 'amharic',
    'ar': 'arabic',
    'an': 'aragonese',
    'hy': 'armenian',
    'as': 'assamese',
    'av': 'avaric',
    'ae': 'avestan',
    'ay': 'aymara',
    'az': 'azerbaijani',
    'bm': 'bambara',
    'ba': 'bashkir',
    'eu': 'basque',
    'be': 'belarusian',
    'bn': 'bengali',
    'bh': 'bihari languages',
    'bi': 'bislama',
    'nb': 'bokmål, norwegian',
    'bs': 'bosnian',
    'br': 'breton',
    'bg': 'bulgarian',
    'my': 'burmese',
    'es': 'castilian',
    'ca': 'catalan',
    'km': 'central khmer',
    'ch': 'chamorro',
    'ce': 'chechen',
    'ny': 'chewa',
    'ny': 'chichewa',
    'zh': 'chinese',
    'za': 'chuang',
    'cu': 'church slavic',
    'cu': 'church slavonic',
    'cv': 'chuvash',
    'kw': 'cornish',
    'co': 'corsican',
    'cr': 'cree',
    'hr': 'croatian',
    'cs': 'czech',
    'da': 'danish',
    'dv': 'dhivehi',
    'dv': 'divehi',
    'nl': 'dutch',
    'dz': 'dzongkha',
    'en': 'english',
    'eo': 'esperanto',
    'et': 'estonian',
    'ee': 'ewe',
    'fo': 'faroese',
    'fj': 'fijian',
    'fi': 'finnish',
    'nl': 'flemish',
    'fr': 'french',
    'ff': 'fulah',
    'gd': 'gaelic',
    'gl': 'galician',
    'lg': 'ganda',
    'ka': 'georgian',
    'de': 'german',
    'ki': 'gikuyu',
    'el': 'greek, modern (1453-)',
    'kl': 'greenlandic',
    'gn': 'guarani',
    'gu': 'gujarati',
    'ht': 'haitian',
    'ht': 'haitian creole',
    'ha': 'hausa',
    'he': 'hebrew',
    'hz': 'herero',
    'hi': 'hindi',
    'ho': 'hiri motu',
    'hu': 'hungarian',
    'is': 'icelandic',
    'io': 'ido',
    'ig': 'igbo',
    'id': 'indonesian',
    'ia': 'interlingua (international auxiliary language association)',
    'ie': 'interlingue',
    'iu': 'inuktitut',
    'ik': 'inupiaq',
    'ga': 'irish',
    'it': 'italian',
    'ja': 'japanese',
    'jv': 'javanese',
    'kl': 'kalaallisut',
    'kn': 'kannada',
    'kr': 'kanuri',
    'ks': 'kashmiri',
    'kk': 'kazakh',
    'ki': 'kikuyu',
    'rw': 'kinyarwanda',
    'ky': 'kirghiz',
    'kv': 'komi',
    'kg': 'kongo',
    'ko': 'korean',
    'kj': 'kuanyama',
    'ku': 'kurdish',
    'kj': 'kwanyama',
    'ky': 'kyrgyz',
    'lo': 'lao',
    'la': 'latin',
    'lv': 'latvian',
    'lb': 'letzeburgesch',
    'li': 'limburgan',
    'li': 'limburger',
    'li': 'limburgish',
    'ln': 'lingala',
    'lt': 'lithuanian',
    'lu': 'luba-katanga',
    'lb': 'luxembourgish',
    'mk': 'macedonian',
    'mg': 'malagasy',
    'ms': 'malay',
    'ml': 'malayalam',
    'dv': 'maldivian',
    'mt': 'maltese',
    'gv': 'manx',
    'mi': 'maori',
    'mr': 'marathi',
    'mh': 'marshallese',
    'ro': 'moldavian',
    'ro': 'moldovan',
    'mn': 'mongolian',
    'na': 'nauru',
    'nv': 'navaho',
    'nv': 'navajo',
    'nd': 'ndebele, north',
    'nr': 'ndebele, south',
    'ng': 'ndonga',
    'ne': 'nepali',
    'nd': 'north ndebele',
    'se': 'northern sami',
    'no': 'norwegian',
    'nb': 'norwegian bokmål',
    'nn': 'norwegian nynorsk',
    'ii': 'nuosu',
    'ny': 'nyanja',
    'nn': 'nynorsk, norwegian',
    'ie': 'occidental',
    'oc': 'occitan (post 1500)',
    'oj': 'ojibwa',
    'cu': 'old bulgarian',
    'cu': 'old church slavonic',
    'cu': 'old slavonic',
    'or': 'oriya',
    'om': 'oromo',
    'os': 'ossetian',
    'os': 'ossetic',
    'pi': 'pali',
    'pa': 'panjabi',
    'ps': 'pashto',
    'fa': 'persian',
    'pl': 'polish',
    'pt': 'portuguese',
    'pa': 'punjabi',
    'ps': 'pushto',
    'qu': 'quechua',
    'ro': 'romanian',
    'rm': 'romansh',
    'rn': 'rundi',
    'ru': 'russian',
    'sm': 'samoan',
    'sg': 'sango',
    'sa': 'sanskrit',
    'sc': 'sardinian',
    'gd': 'scottish gaelic',
    'sr': 'serbian',
    'sn': 'shona',
    'ii': 'sichuan yi',
    'sd': 'sindhi',
    'si': 'sinhala',
    'si': 'sinhalese',
    'sk': 'slovak',
    'sl': 'slovenian',
    'so': 'somali',
    'st': 'sotho, southern',
    'nr': 'south ndebele',
    'es': 'spanish',
    'su': 'sundanese',
    'sw': 'swahili',
    'ss': 'swati',
    'sv': 'swedish',
    'tl': 'tagalog',
    'ty': 'tahitian',
    'tg': 'tajik',
    'ta': 'tamil',
    'tt': 'tatar',
    'te': 'telugu',
    'th': 'thai',
    'bo': 'tibetan',
    'ti': 'tigrinya',
    'to': 'tonga (tonga islands)',
    'ts': 'tsonga',
    'tn': 'tswana',
    'tr': 'turkish',
    'tk': 'turkmen',
    'tw': 'twi',
    'ug': 'uighur',
    'uk': 'ukrainian',
    'ur': 'urdu',
    'ug': 'uyghur',
    'uz': 'uzbek',
    'ca': 'valencian',
    've': 'venda',
    'vi': 'vietnamese',
    'vo': 'volapük',
    'wa': 'walloon',
    'cy': 'welsh',
    'fy': 'western frisian',
    'wo': 'wolof',
    'xh': 'xhosa',
    'yi': 'yiddish',
    'yo': 'yoruba',
    'za': 'zhuang',
    'zu': 'zulu'
};

exports.codeToLanguage = codeToLanguage;
